### ISSUE TITLE
Feature: Support for Mac OSX

### ISSUE THREAD

**Issue by androchentw** [ArthurHub/Productivity-Tools#1]
Hi Arthur,

I came across this great repo and was wondering how this could be used on Mac OS.
Could you please kindly point out whether it's possible, or the way to use it?
Thanks!

**Comment by ArthurHub** [comment]
well the core code should run on mono but the UI is written in WPF so it needs to be converted to winforms or create an asp.next site from it...
also if you are interested in the one note converter it may not work well as each one note version create a slightly different html.

**Comment by androchentw** [comment]
Okay I got it!
Thanks!
